spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/financetracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate # or update while developing
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
