version: "3.9"

services:
  db:
    image: postgres:15
    container_name: finance_db
    environment:
      POSTGRES_DB: financetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d financetracker"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: finance_backend
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financetracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      FRONTEND_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: finance_frontend
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules

volumes:
  db_data:
