version: "3.9"

services:
  backend:
    image: eclipse-temurin:21-jdk
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../backend:/app
      - ~/.gradle:/root/.gradle
    command: >
      bash -lc "chmod +x ./gradlew &&
                ./gradlew bootRun --args=--spring.profiles.active=postgres"
