services:
  db:
    image: postgres:16
    container_name: infra-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financetracker
    ports:
      - "15432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d financetracker"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

volumes:
  dbdata:
