name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'finance-tracker/backend/**'
              - '.github/workflows/**'
            frontend:
              - 'finance-tracker/frontend/**'
              - '.github/workflows/**'

  backend:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Spotless & Tests
        run: ./gradlew --no-daemon --stacktrace spotlessCheck test

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Upload JUnit results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-junit
          path: |
            finance-tracker/backend/build/test-results/test
            finance-tracker/backend/build/reports/tests/test
          if-no-files-found: ignore

      - name: Upload Jacoco (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-jacoco
          path: finance-tracker/backend/build/reports/jacoco/**
          if-no-files-found: ignore

  frontend:
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload frontend build (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: finance-tracker/frontend/dist
          if-no-files-found: ignore
