name: Release (Docker)

on:
  push:
    tags: ["v*"]

jobs:
  backend-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: finance-tracker/backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: finance-tracker/backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/finance-tracker-backend:${{ github.ref_name }}
